# Make a static library

ROOT_DIR        = ./../../..
SOURCE_DIR      = ./../Src
DEPENDENCIES    = Http TcpServer AppUtils Core
LIBTARGET       = libserversentevents.a

-include $(ROOT_DIR)/Tools/build.mk