# Make a static library

SOURCEDIR       = ./../Src
LIBDIR          = ./../..
TOOLDIR         = ./../../../Tools/
SOURCES         = $(wildcard $(SOURCEDIR)/*.cpp)
DEPENDENCIES    = Router AppUtils Core Xml
LINKS           = -lpthread
LIBTARGET       = libtcpserver.a

-include $(TOOLDIR)/build.mk