# Make a static library

ROOT_DIR        = ./../../..
SOURCE_DIR      = ./../Src
DEPENDENCIES    = Simulation AppUtils Math Core
LIBTARGET       = libsimcomponents.a

-include $(ROOT_DIR)/Tools/build.mk