# Make a static library

SOURCEDIR       = ./../Src
LIBDIR          = ./../..
TOOLDIR         = ./../../../Tools/
SOURCES         = $(wildcard $(SOURCEDIR)/*.cpp)
DEPENDENCIES    = 
LINKS           = -lpthread
LIBTARGET       = libcore.a

-include $(TOOLDIR)/build.mk
