# create an executable

ROOT_DIR        = ./../../..
SOURCE_DIR      = ./../Src
DEPENDENCIES    = ServerSentEvents Websockets Router Http TcpServer SimComponents Simulation AppUtils Core
TARGET          = server

-include $(ROOT_DIR)/Tools/build.mk # DO NOT DELETE
