# Make a static library

ROOT_DIR        = ./../../..
SOURCE_DIR      = ./../Src
DEPENDENCIES    = Http TcpServer Simulation AppUtils Core
LIBTARGET       = librouter.a

-include $(ROOT_DIR)/Tools/build.mk