# create an executable

ROOT_DIR        = ./../../..
SOURCE_DIR      = ./../Src
DEPENDENCIES    = ServerSentEvents Websockets Router Http TcpServer AppUtils Core
TARGET          = testapp

-include $(ROOT_DIR)/Tools/build.mk # DO NOT DELETE
