# Make a static library

SOURCEDIR       = ./../Src
LIBDIR          = ./../..
TOOLDIR         = ./../../../Tools/
SOURCES         = $(wildcard $(SOURCEDIR)/*.cpp)
DEPENDENCIES    = Core
LINKS           = -lpthread
LIBTARGET       = libhttp.a

-include $(TOOLDIR)/build.mk