
ROOT_DIR?=.

INSTALL_DIR=${ROOT_DIR}/Install
DOWNLOAD_DIR=${ROOT_DIR}/Download
EXTERNAL_DIR=${ROOT_DIR}/External
APP_DIR=${ROOT_DIR}/App
WEB_DIR=${ROOT_DIR}/Web
LIB_DIR=${ROOT_DIR}/Lib
TEST_DIR=${ROOT_DIR}/Test
